### ISSUE TITLE
Erro ao redirecionar para o Linkedin

### ISSUE THREAD

**Issue by rebecanonato89** [luisfernandodass/portfolio-1#1]
Ao redirecionar para o linkedin ele carrega a url incorretamente

![image](https://user-images.githubusercontent.com/38442994/130624136-f2a1edf5-fad4-4146-b27b-22d9f8c9f43b.png)

**Comment by luisfernandodass** [comment]
Estava faltando uma barra depois do https, acabei de corrigir, muito obrigado por ter gasto seu tempo me alertando!!!
